// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetUsersResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A JSON array of user names
	GetUsers200ApplicationJSONStrings []string
}
